# 開発環境用DBマイグレーション設定
development:
  dialect: postgres
  dir: db/migrate
  datasource: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSLMODE}"
