# fly.toml app configuration file generated for optical-backend on 2026-01-16T20:33:54+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'optical-backend'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[files]]
  guest_path = '/app/optical-github.private-key.pem'
  secret_name = 'GITHUB_PRIVATE_KEY_PEM'

[[vm]]
  cpus = 1
  memory_mb = 1024
