name: ai-review
on:
  workflow_dispatch:
  pull_request:
permissions:
  contents: write
  pull-requests: write
jobs:
  my-job:
    name: opencode
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: rmacklin/fetch-through-merge-base@v0
      - run: echo "$(git diff ${{ github.base_ref }})"

      - uses: oven-sh/setup-bun@v2
      - run: bun install -g opencode-ai
      - run: opencode run --agent=review "$(git diff ${{ github.base_ref }})" > ai-review.md

      - name: PR comment with file
        uses: mshick/add-pr-comment@v2
        with:
          message-path: ai-review.md
