name: AI-Review
on:
  workflow_dispatch:
  push:
permissions:
  contents: write
  pull-requests: write
jobs:
  my-job:
    name: grok-code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - run: bun install -g opencode-ai
      - run: opencode run --agent=review "review $(git diff $(git merge-base HEAD main))" > ai-review.md

      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v3
        with:
          message-path: ai-review.md
          refresh-message-position: true
