name: Deploy Image
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  deploy-ghcr:
    runs-on: ubuntu-latest
    steps:
      # リポジトリにチェックアウト
      - name: checkout
        uses: actions/checkout@v4
      # イメージをビルド
      - name: build docker image
        run: |
          REPO=${{ github.repository }}
          docker build -t ghcr.io/${REPO,,}:latest .
      # Dockerにログイン
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      # イメージをデプロイ
          docker push ghcr.io/${REPO,,}:latest

